package com.neptuo.os.fsys.data.model;
// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA

import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Directory generated by hbm2java
 */
@Entity
@Table(name = "fsys_directory")
@Serializable(name="folder")
@Deserializable(name="folder")
public class Directory extends FileSystemItem implements java.io.Serializable {

    private static final long serialVersionUID = -3427255603388318445L;

    public Directory() {
        super();
        parent = null;
    }

    public Directory(Set<FileSystemPermission> permissions) {
        super();
        setPermissions(permissions);
    }
}
