package com.neptuo.os.fsys.data.model;

// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA
import com.neptuo.data.model.AbstractEntity;
import com.neptuo.os.core.data.model.User;
import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.validator.constraints.Length;

/**
 * Drive generated by hbm2java
 */
@Entity
@Table(name = "fsys_drive")
@Serializable(name = "drive")
@Deserializable(name = "drive")
public class Drive extends AbstractEntity implements java.io.Serializable {

    private Long id;
    private String name;
    private String label;
    private User owner;
    private Directory directory;
    private String url;
    private String physicalPath;

    public Drive() {
    }

    public Drive(Long id) {
        this.id = id;
    }

    public Drive(Long id, String name, Directory directory) {
        this.id = id;
        this.name = name;
        this.directory = directory;
    }

    @Id
    @GeneratedValue
    @Override
    @Serializable(name = "id", primary = true)
    public Long getId() {
        return this.id;
    }

    @Deserializable(name = "id")
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    @Length(max = 50)
    @Serializable(name = "name")
    public String getName() {
        return this.name;
    }

    @Deserializable(name = "name")
    public void setName(String name) {
        this.name = name;
    }

    @Serializable(name = "label")
    public String getLabel() {
        return label;
    }

    @Deserializable(name = "label")
    public void setLabel(String label) {
        this.label = label;
    }

    @ManyToOne
    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    public Directory getDirectory() {
        return directory;
    }

    public void setDirectory(Directory directory) {
        this.directory = directory;
    }

    @Serializable(name = "url")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPhysicalPath() {
        return physicalPath;
    }

    public void setPhysicalPath(String physicalPath) {
        this.physicalPath = physicalPath;
    }

    // Serialization -----------------------------------------------------------
    
    @Transient
    @Serializable(name = "folderId")
    public Long getDirectoryId() {
        return directory.getId();
    }

    @Deserializable(name = "folderId")
    public void setDirectoryId(Long id) {
        if (directory == null) {
            directory = new Directory();
        }
        directory.setId(id);
    }

    @Deserializable(name = "ownerId")
    public void setOwnerId(Long id) {
        if (owner == null) {
            owner = new User();
        }
        owner.setId(id);
    }

    @Transient
    @Serializable(name = "isSystem")
    public boolean getIsSystem() {
        return owner == null;
    }
}
