package com.neptuo.os.fsys.data.model;
// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA

import com.neptuo.os.core.data.model.User;
import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "fsys_file")
@Serializable(name="file")
@Deserializable(name="file")
public class File extends FileSystemItem implements java.io.Serializable {
    private static final long serialVersionUID = 1175064466243063049L;
    
    private User owner;
    private String type;
    private String uploadKey;

    private Long size;

    public File() {
        super();
    }

    public File(User owner, String type, Set<FileSystemPermission> permissions) {
        super();
        this.owner = owner;
        this.type = type;
        setPermissions(permissions);
    }

    @ManyToOne
    public User getOwner() {
        return this.owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    @Column(name = "type", length = 50, nullable = false)
    @Length(max = 50)
    @NotNull
    @Serializable(name="type")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Transient
    public String getUploadKey() {
        return uploadKey;
    }

    @Deserializable(name="uploadKey")
    public void setUploadKey(String uploadKey) {
        this.uploadKey = uploadKey;
    }

    //Serialization ------------------------------------------------------------

    @Transient
    @Serializable(name="ownerId")
    public Long getOwnerId() {
        return owner.getId();
    }

    @Transient
    @Serializable(name="ownerDisplayName")
    public String getOwnerDisplayName() {
        return owner.getDisplayName();
    }

    @Transient
    @Serializable(name="size")
    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }
}
