package com.neptuo.os.core.data.model;
// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA

import com.neptuo.data.model.AbstractEntity;
import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.constraints.Length;

/**
 * AccessType generated by hbm2java
 */
@Entity
@Table(name = "core_accesstype")
@Serializable(name="accessType")
@Deserializable(name="accessType")
public class AccessType extends AbstractEntity implements java.io.Serializable {

    private static final long serialVersionUID = 5182060875486476822L;
    private Long id;
    private int level;
    private String name;
    private String category;

    public AccessType() {
    }

    public AccessType(String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue
    @Override
    @Serializable(name="id", primary=true)
    public Long getId() {
        return this.id;
    }

    @Deserializable(name="id")
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", length = 20, unique = true)
    @Length(max = 20)
    @Serializable(name="name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "category", length = 20)
    @Length(max = 20)
    @Serializable(name="category")
    public String getCategory() {
        return category;
    }

    @Deserializable(name="category")
    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name="perm_level")
    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }
}
