package com.neptuo.os.core.data.model;
// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA

import com.neptuo.data.model.AbstractEntity;
import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Identitybase generated by hbm2java
 */
@Entity
@Table(name = "core_identitybase")
@Inheritance(strategy = InheritanceType.JOINED)
@Serializable(name = "identity")
@Deserializable(name = "identity")
public abstract class IdentityBase extends AbstractEntity implements java.io.Serializable {

    private static final long serialVersionUID = 7207264061134973403L;
    private Long id;

    public IdentityBase() {
    }

    public IdentityBase(Long id) {
        this.id = id;
    }

    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    @Serializable(name = "id", primary = true)
    @Override
    public Long getId() {
        return this.id;
    }

    @Deserializable(name = "id")
    public void setId(Long id) {
        this.id = id;
    }

    @Transient
    @Serializable(name = "displayName")
    public abstract String getDisplayName();

    @Transient
    @Serializable(name = "type")
    public String getType() {
        return this instanceof User ? "user" : "userrole";
    }
}
