package com.neptuo.os.core.data.model;
// Generated Apr 24, 2010 12:14:52 PM by Hibernate Tools 3.2.4.GA

import com.neptuo.service.io.annotation.Deserializable;
import com.neptuo.service.io.annotation.Serializable;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Length;

/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name = "core_userrole")
@Serializable(name="role")
@Deserializable(name="role")
public class UserRole extends IdentityBase implements java.io.Serializable {
    private static final long serialVersionUID = 202185987016702035L;

    private UserRole parent;
    private Set<UserRole> chidren;
    private String name;

    public UserRole() {
    }

    public UserRole(String name) {
        super();
        this.name = name;
    }

    @Column(name = "name", length = 30, unique=true)
    @Length(min = 5, max = 30)
    @Serializable(name="name")
    public String getName() {
        return this.name;
    }

    @Deserializable(name="name")
    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(mappedBy = "parent")
    public Set<UserRole> getChidren() {
        return chidren;
    }

    public void setChidren(Set<UserRole> chidren) {
        this.chidren = chidren;
    }

    @ManyToOne
    public UserRole getParent() {
        return parent;
    }

    public void setParent(UserRole parent) {
        this.parent = parent;
    }

    @Transient
    @Serializable(name="parentId")
    public Long getParentId() {
        if(parent != null)
            return parent.getId();
        return null;
    }

    @Deserializable(name="parentId")
    public void setParentId(Long id) {
        if(parent == null)
            parent = new UserRole();
        parent.setId(id);
    }

    @Override
    @Transient
    @Serializable(name="displayName")
    public String getDisplayName() {
        return getName();
    }
}
